### ISSUE TITLE
可以适用于其他服务器吗?

### ISSUE THREAD

**Issue by 1-riverfish** [zce/douban-api-proxy#10]
首先谢谢博主提供的方法!
  我先用您的没有问题,然后照着readmd文档在自己的云服务器上配置了一下,但结果发现仍然有限速,即反向代理并未起作用,ngnix唯一的区别是我没有配置ssl,可能是哪里出问题了?
谢谢!

**Comment by 1-riverfish** [comment]
报的是400错误,设置过请求头的
Content-Type 为 json.

**Comment by zce** [comment]
当然可以部署到自己的服务器，但是限速问题任然存在，我的代理中额外添加了一个 App key，所以限额会大一些。

至于 400 就应该是你客户端请求时有问题，大多数情况是因为你的请求 Header 中的 `Content-Type` 设置成了 `application/json`，而豆瓣 API 对这一项是有限制的，目前应该只要不是 `application/json` 都没问题

**Comment by 1-riverfish** [comment]
谢谢!可是我限速是单个IP 100,并且请求头中已经设置了Content-Type....不知为何仍然会提示超速

**Comment by zce** [comment]
限速问题我也无法帮你解决，你可以自己找一个 Key，我可以告诉你怎么配置

**Comment by 1-riverfish** [comment]
好的,十分感谢!
