### ISSUE TITLE
你用的是内部apiKey么？我自己好几年的apiKey，这个月全都403 Forbiddent了？

### ISSUE THREAD

**Issue by JunjieW** [zce/douban-api-proxy#13]

**Comment by zce** [comment]
这个不太清楚，应该没有什么内部的说法

**Comment by JunjieW** [comment]
不好意思，追着问一个问题-- 我只是比较好奇为什么你的apiKey至今还能用，因为你在README里提到：
> 我搭建的这个免费的服务中接口权限更高，可以使用影评、图书、音乐之类的接口，原因是我在代理请求的同时额外添加了一个 apikey 查询参数（由于特殊原因就不公开这个 KEY 了）。

我自己的apiKey如今好像根本没法从douban官方api里获取任何数据了，所有请求都是403 Forbidden，所以比较好奇这个"接口权限更高"的apiKey是什么类型的、或者是怎么申请到的？我也想去升级(或是修复、解冻)我的apiKey.

从网上零星的消息来看，豆瓣好像要把他们的API（至少是图书API）关掉了:
  - https://www.v2ex.com/t/485687
  - https://www.douban.com/group/topic/123746666/  （看到你在这个帖子里安利了你的代理API，所以你的apiKey是非个人开发者的key么？）
