### ISSUE TITLE
电影搜索接口不可用

### ISSUE THREAD

**Issue by SherlockedTxh** [zce/douban-api-proxy#15]
如下：
~~~
https://douban.uieee.com/v2/movie/search?q=Aladdin
~~~
返回：
~~~
{"msg":"uri_not_found","code":1001,"request":"GET \/v2\/movie\/search"}
~~~

**Comment by zce** [comment]
README 中已经说明过这个问题

**Comment by SherlockedTxh** [comment]
> README 中已经说明过这个问题

可是书籍和音乐搜索都ok，就电影有问题。

**Comment by zce** [comment]
> > README 中已经说明过这个问题
> 
> 可是书籍和音乐搜索都ok，就电影有问题。

跟这个没关系，首先你要理解代理的含义，源头上出了问题，代理如何解决？

**Comment by BWmelon** [comment]
> > README 中已经说明过这个问题
> 
> 可是书籍和音乐搜索都ok，就电影有问题。

可以试一下这个
`https://movie.douban.com/j/subject_suggest?q=追龙`

**Comment by songguowei** [comment]
> > > README 中已经说明过这个问题
> > 
> > 
> > 可是书籍和音乐搜索都ok，就电影有问题。
> 
> 可以试一下这个
> `https://movie.douban.com/j/subject_suggest?q=追龙`

这个没什么用，信息不全连演员都没有

**Comment by hobs1706** [comment]
> > > README 中已经说明过这个问题
> > 
> > 
> > 可是书籍和音乐搜索都ok，就电影有问题。
> 
> 可以试一下这个
> `https://movie.douban.com/j/subject_suggest?q=追龙`

这接口还能用吗 晚上试的蛮开心的 拉泡尿就没了

**Comment by okcodycom** [comment]
在 [豆瓣电影](https://movie.douban.com/) 中，有几个接口，我用来写小案例能用，有学习需要可以试试：

## 获取标签

**请求方法：** GET

**请求URL：** https://movie.douban.com/j/search_tags

**请求参数：**

| 参数名 | 类型   | 必要 | 缺省  | 说明               |
| ------ | ------ | ---- | ----- | ------------------ |
| type   | string | 否   | movie | 电影/电视剧/(不明) |
| source | 不明   | 否   | index | 不明               |

**请求示例：**

- 电影

```
GET https://movie.douban.com/j/search_tags
```

- 电视剧

```
GET https://movie.douban.com/j/search_tags?type=tv
```

```json
{
	"tags": ["热门", "美剧", "英剧", "韩剧", "日剧", "国产剧", "港剧", "日本动画", "综艺", "纪录片"]
}
```

## 获取电影

**请求方法：** GET

**请求URL：** https://movie.douban.com/j/search_subjects

**请求参数：**

| 参数名     | 类型   | 必要 | 缺省  | 说明                   |
| ---------- | ------ | ---- | ----- | ---------------------- |
| type       | string | 否   | movie | 电影/电视剧/(不明)     |
| tag        | string | 是   |       | 标签                   |
| page_limit | number | 否   | 20    | 返回的电影条目数量     |
| page_start | number | 否   | 0     | 返回电影条目的开始位置 |

**请求示例：**

- 电影

```
GET https://movie.douban.com/j/search_subjects?tag=热门
```

```json
{
	"subjects": [{
		"rate": "8.5",
		"cover_x": 3158,
		"title": "1917",
		"url": "https://movie.douban.com/subject/30252495/",
		"playable": false,
		"cover": "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2570243317.webp",
		"id": "30252495",
		"cover_y": 5000,
		"is_new": false
	}]
}
```

- 电视剧

```
https://movie.douban.com/j/search_subjects?type=tv&tag=热门
```

```json
{
	"subjects": [{
		"rate": "9.2",
		"cover_x": 2953,
		"title": "想见你",
		"url": "https://movie.douban.com/subject/30468961/",
		"playable": true,
		"cover": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2576977981.webp",
		"id": "30468961",
		"cover_y": 4134,
		"is_new": false
	}]
}
```

> **标签不需要按照获取的来，直接传想搜的电影也OK**
>
> ```
> GET https://movie.douban.com/j/search_subjects?tag=当幸福来敲门
> ```
>
> ```
> GET https://movie.douban.com/j/search_subjects?tag=钢铁侠
> ```

## 获取电影条目详情

**请求方法：** GET

**请求URL：** https://movie.douban.com/j/subject_abstract

**请求参数：**

| 参数名     | 类型   | 必要 | 缺省 | 说明          |
| ---------- | ------ | ---- | ---- | ------------- |
| subject_id | number | 是   |      | 电影条目的 ID |

**请求示例：**

```
GET https://movie.douban.com/j/subject_abstract?subject_id=4917832
```

**Comment by Lotus-Blue** [comment]
> 在 [豆瓣电影](https://movie.douban.com/) 中，有几个接口，我用来写小案例能用，有学习需要可以试试：
> 
> ## 获取标签
> **请求方法：** GET
> 
> **请求URL：** https://movie.douban.com/j/search_tags
> 
> **请求参数：**
> 
> 参数名	类型	必要	缺省	说明
> type	string	否	movie	电影/电视剧/(不明)
> source	不明	否	index	不明
> **请求示例：**
> 
> * 电影
> 
> ```
> GET https://movie.douban.com/j/search_tags
> ```
> 
> * 电视剧
> 
> ```
> GET https://movie.douban.com/j/search_tags?type=tv
> ```
> 
> ```json
> {
> 	"tags": ["热门", "美剧", "英剧", "韩剧", "日剧", "国产剧", "港剧", "日本动画", "综艺", "纪录片"]
> }
> ```
> 
> ## 获取电影
> **请求方法：** GET
> 
> **请求URL：** https://movie.douban.com/j/search_subjects
> 
> **请求参数：**
> 
> 参数名	类型	必要	缺省	说明
> type	string	否	movie	电影/电视剧/(不明)
> tag	string	是		标签
> page_limit	number	否	20	返回的电影条目数量
> page_start	number	否	0	返回电影条目的开始位置
> **请求示例：**
> 
> * 电影
> 
> ```
> GET https://movie.douban.com/j/search_subjects?tag=热门
> ```
> 
> ```json
> {
> 	"subjects": [{
> 		"rate": "8.5",
> 		"cover_x": 3158,
> 		"title": "1917",
> 		"url": "https://movie.douban.com/subject/30252495/",
> 		"playable": false,
> 		"cover": "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2570243317.webp",
> 		"id": "30252495",
> 		"cover_y": 5000,
> 		"is_new": false
> 	}]
> }
> ```
> 
> * 电视剧
> 
> ```
> https://movie.douban.com/j/search_subjects?type=tv&tag=热门
> ```
> 
> ```json
> {
> 	"subjects": [{
> 		"rate": "9.2",
> 		"cover_x": 2953,
> 		"title": "想见你",
> 		"url": "https://movie.douban.com/subject/30468961/",
> 		"playable": true,
> 		"cover": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2576977981.webp",
> 		"id": "30468961",
> 		"cover_y": 4134,
> 		"is_new": false
> 	}]
> }
> ```
> 
> > **标签不需要按照获取的来，直接传想搜的电影也OK**
> > ```
> > GET https://movie.douban.com/j/search_subjects?tag=当幸福来敲门
> > ```
> > 
> > 
> > ```
> > GET https://movie.douban.com/j/search_subjects?tag=钢铁侠
> > ```
> 
> ## 获取电影条目详情
> **请求方法：** GET
> 
> **请求URL：** https://movie.douban.com/j/subject_abstract
> 
> **请求参数：**
> 
> 参数名	类型	必要	缺省	说明
> subject_id	number	是		电影条目的 ID
> **请求示例：**
> 
> ```
> GET https://movie.douban.com/j/subject_abstract?subject_id=4917832
> ```

这个我早就知道了，容易被封ip，没意思

**Comment by LinHouYu** [comment]
大佬您的 https://movie.douban.com/j/search_subjects 接口哪里找到的？
我通过DevTools → Network → XHR/Fetch 找不到这个JSON请求，可以说说吗？
