### ISSUE TITLE
除了第一个，其他代理都挂了呢

### ISSUE THREAD

**Issue by Hbxuan** [zce/douban-api-proxy#25]
https://douban.uieee.com （只有这个还活着）
下面的这些似乎都挂了
https://douban-api.uieee.com
https://douban-api.now.sh
https://douban-api.zce.now.sh
https://douban-api-git-master.zce.now.sh

**Comment by zce** [comment]
请提供页面错误描述

**Comment by zce** [comment]
ping @Hbxuan
