### ISSUE TITLE
invalid_apikey

### ISSUE THREAD

**Issue by gclirsky** [zce/douban-api-proxy#26]
NGINX set referer 之后，访问 `/v2/book/search?q=xxx`，返回invalid_apikey，由于豆瓣api持续维护中，apikey暂不对个人开放申请；是不是没有你额外加的apikey，无法自行搭建代理服务？

> 我搭建的这个免费的服务中接口权限更高，可以使用影评、图书、音乐之类的接口，原因是我在代理请求的同时额外添加了一个 apikey 查询参数

```json
{
   "msg": "invalid_apikey",
   "code": 104,
   "request": "GET /v2/book/search?q=xxx"
}
```

**Comment by zce** [comment]
搭建代理与 apikey 没有必要的关系，apikey 只会影响你请求官方地址时的权限。
