### ISSUE TITLE
没有review的接口吗？

### ISSUE THREAD

**Issue by nectx** [zce/douban-api-proxy#34]
大佬，不敢耽误你时间，我来回看了好几遍你的文档 https://douban-api-docs.zce.me/book.html ，但是只有图书接口，没有图书书评的接口，但是文档中有书评的 json 字段，请问是遗漏了书评接口，还是本本就么有？
没有的话，您是怎么知道书评字段 json 结构的？
盼回复。

**Comment by zce** [comment]
[接口](https://github.com/zce/douban-api-proxy) 是代理到豆瓣的官方 API，代理过程只是修改了 Referer（为了解决屏蔽小程序问题）、添加额外的 apiKey（为了部分特殊接口的访问）、支持 CORS，其余的都跟官方 API 没有区别。

[文档](https://github.com/zce/douban-api-docs) 是我从之前的 [网页历史博物馆](https://archive.org) 中整理出来的豆瓣 API 官方文档，只是修正了部分格式和明显的字面错误。

也就是说，对于官方 API 本身的问题，我并没有特殊处理（很多事情无能为力），其中包括（不限于）：

- 搜索接口无法调用问题
- 接口实际调用与文档不一致
- 接口限额问题，目前每个代理地址的限额是（10000/h）

特此说明。

**Comment by nectx** [comment]
thx
