### ISSUE TITLE
获取电影详情的问题

### ISSUE THREAD

**Issue by SuiKaSan** [zce/douban-api-proxy#35]
我想请问为什么我用浏览器获取电影详情就可以获取，但在项目中使用axios获取就会报403错误呢？提示我缺少apikey。

**Comment by zce** [comment]
你可以提供一个错误问题的复现用例么

**Comment by SuiKaSan** [comment]
> 你可以提供一个错误问题的复现用例么

之前是我用错了请求方法，但用回文档中的GET请求方式后还是报错，报了400错误，提示invalid access_token。

**Comment by SuiKaSan** [comment]
> 你可以提供一个错误问题的复现用例么

之前是我用错了请求方法，但用回文档中的GET请求方式后还是报错，报了400错误，提示invalid access_token。
用axios获取，项目中已经用vue-cli设置了跨域。
代码如下:

```
// douban是跨域别名，原始链接是 https://douban.uieee.com/v2
this.$axios.get(`douban/movie/subject/${id}`).then(res => {
    console.log(res)
}).catch(err => {
    console.log(err)
}) 
```
  就是非常基础的获取数据操作，传入id之后获取后报错如下：
![image](https://user-images.githubusercontent.com/44567811/71237951-d9117a80-233d-11ea-8753-adb27c3488d8.png)

**Comment by SuiKaSan** [comment]
> > 你可以提供一个错误问题的复现用例么
> 
> 之前是我用错了请求方法，但用回文档中的GET请求方式后还是报错，报了400错误，提示invalid access_token。
> 用axios获取，项目中已经用vue-cli设置了跨域。
> 代码如下:
> 
> ```
> // douban是跨域别名，原始链接是 https://douban.uieee.com/v2
> this.$axios.get(`douban/movie/subject/${id}`).then(res => {
>     console.log(res)
> }).catch(err => {
>     console.log(err)
> }) 
> ```
> 
> 就是非常基础的获取数据操作，传入id之后获取后报错如下：
> ![image](https://user-images.githubusercontent.com/44567811/71237951-d9117a80-233d-11ea-8753-adb27c3488d8.png)

并且这个请求链接在网页直接输入的话是可以获取到数据的

**Comment by SuiKaSan** [comment]
> 你可以提供一个错误问题的复现用例么

并且这个请求链接在网页直接输入的话是可以获取到数据的

**Comment by SuiKaSan** [comment]
> 你可以提供一个错误问题的复现用例么

我自己搞懂了，是因为我每次请求都带上了自己网站的token，所以才会报错，把token去掉就没事了，我接下来就想想怎么把对外部豆瓣接口的请求不带上token就可以了。不好意思，麻烦您了，还有谢谢您。
