### ISSUE TITLE
api return `invalid_request_scheme: http`

### ISSUE THREAD

**Issue by sinchang** [zce/douban-api-proxy#36]
should we update proxy target to `https://api.douban.com`?

**Comment by zce** [comment]
I'm not sure I understand what the issue here is. Could you provide a reproduction?

**Comment by sinchang** [comment]
just visit https://douban-api.now.sh/v2/book/user/kentzhu/collections?status=read&count=10

**Comment by zce** [comment]
https://douban-api-git-http-to-https.zce.now.sh/v2/book/user/kentzhu/collections?status=read&count=10

**Comment by sinchang** [comment]
@zce thank you
