### ISSUE TITLE
关于服务器证书无效的问题

### ISSUE THREAD

**Issue by SunRelease** [zce/douban-api-proxy#39]
大佬好,最近好像第一个网址:https://douban.uieee.com/v2/movie/证书是无效的,小程序无法请求数据,但是还是非常感谢您能提供这个机会给我们测试小程序,非常感谢!!

**Comment by zce** [comment]
@SunRelease 已更新证书

**Comment by bobpan** [comment]
@zce 大佬好，我也遇到这个问题，从浏览器访问提示证书不可信，有什么好办法可以解决？

**Comment by SY1123** [comment]
> @zce 大佬好，我也遇到这个问题，从浏览器访问提示证书不可信，有什么好办法可以解决？

同遇到。。难道是限流了？

**Comment by bobpan** [comment]
补一个错误消息：

![image](https://user-images.githubusercontent.com/5138465/78670988-36433300-7911-11ea-9b78-9076453775a5.jpeg)
