### ISSUE TITLE
某些api请求提示没有权限

### ISSUE THREAD

**Issue by blogwy** [zce/douban-api-proxy#5]
作者，你好！

我用了你的nginx配置，反向代理豆瓣电影api，发现有些api请求提示没有权限。具体json
`{
"msg": "need_permission",
"code": 1000,
"request": "GET /v2/movie/subject/1291546/comments"
}`
同样的请求，你的代理可以正常返回数据。

返回异常的url：（目前就测试了这两个返回有误，其他的不知道）
/v2/movie/subject/1291546/comments
/v2/movie/subject/1291546/reviews

返回正常的url：
/v2/movie/top250
/v2/movie/us_box

我的代理url：
https://api.blogwy.com

**Comment by zce** [comment]
我的代理配置中不仅仅包含基本的代理配置，还配有额外权限的 API KEY（也就是说通过 douban.uieee.com 访问会有额外权限），如果你也有 KEY 的话就可以跟我配的一样

**Comment by blogwy** [comment]
我没有API KEY，豆瓣目前不支持个人开发者申请API KEY。

**Comment by blogwy** [comment]
您的API KEY是怎么申请到的？

**Comment by zce** [comment]
我找的是之前的一个项目中用的 KEY，以企业资格申请的，目前官方确实关闭了申请入口

**Comment by blogwy** [comment]
我刚刚在别人的项目里面找到一个key，[jokermonn/-Api](https://github.com/jokermonn/-Api/blob/master/DoubanMovie.md)。谢了！
