### ISSUE TITLE
请问 在小程序中只有第一次调用可以使用，在后续页面第二次调用的时候 就400bad request了

### ISSUE THREAD

**Issue by yang1015** [zce/douban-api-proxy#7]
比如我在首页调用了https://douban.uieee.com/v2/movie/in_theaters?start=0&count=4
然后再点击查看更多的时候 再使用https://douban.uieee.com/v2/movie/in_theaters
就会报400，本来以为是没有加start count参数的问题，但是即便加上了还是400
求解

**Comment by yang1015** [comment]
其实点击访问链接 是有很多数据的 postman也没问题
可是小程序里报错是咋回事呢

**Comment by yang1015** [comment]
其实点击访问链接 是有很多数据的
可是小程序里报错是咋回事呢

**Comment by zce** [comment]
Duplicate of #6.
